name: Run tests on supported Elixir/OTP versions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test - OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - { elixir: "1.18.x", otp: "26.x" }
          - { elixir: "1.18.x", otp: "27.x" }
          - { elixir: "1.19.x", otp: "27.x" }
          - { elixir: "1.19.x", otp: "28.x" }
          - { elixir: "1.20.x", otp: "28.x" }
          - { elixir: "1.20.x", otp: "29.x" }
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          install-rebar: true
          install-hex: true

      - name: Retrieve Build Cache
        uses: actions/cache@v4
        id: build-folder-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v4
        id: deps-cache
        with:
          path: deps
          key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix test
